#!/usr/bin/python
import sys
import os
import time

basename = 'osckar-core-debug'
description = 'Runs core services on PORT'
usage="Usage: %s PORT\n%s" % (basename, description)


if len(sys.argv) < 2:
    print basename + ": missing port operand"
    print usage
    sys.exit(1)

port = sys.argv[1]

#core components
os.system('gnome-terminal --command="python /usr/local/bin/osckar/services/EventChatd.py ' + port + '" &')
time.sleep(1)
print 'running PolicyManager with sudo for now, should fix ownership to run as special user'
os.system('gnome-terminal --command="sudo python /usr/local/bin/osckar/services/PolicyManager.py ' + port + '" &')
print 'running VMMInterface with sudo for now, should fix ownership to run as special user'
os.system('gnome-terminal --command="sudo python /usr/local/bin/osckar/interfaces/VMMinterface.py ' + port + '" &')
print 'running Builder with sudo for now, should fix ownership to run as special user'
os.system('gnome-terminal --command="sudo python /usr/local/bin/osckar/interfaces/BuilderInterface.py ' + port + '" &')


#testClient
os.system('gnome-terminal --command="python /usr/local/bin/osckar/interfaces/testClient.py ' + port + '" &')
