#!/bin/bash

su builderinterface -c "osckar-interface-builder $1" &
sleep 1
builder_pid=`pidof -xs osckar-interface-builder`
su builderinterface -c "echo ${builder_pid} > /var/run/builderinterface/builderinterface.pid"