#!/bin/bash

if [ $1 == "-f" ] #run in foreground
then
    su eventchat -c "eventchat  $2" 
else
    su eventchat -c "eventchat  $1" &
    sleep 1
    eventchat_pid=`pidof -xs eventchat`
    su eventchat -c "echo ${eventchat_pid} > /var/run/eventchat/eventchat.pid"
fi